<?php
/**
 * @file
 * CC Badges
 */

/**
 * Implements hook_menu().
 */
function islandora_cc_badge_menu() {
  return array(
    'admin/islandora/tools/badges/creativecommons' => array(
      'title' => 'CC badge',
      'description' => 'Configure Creative Commons badge settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_cc_badge_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_cc_badge_block_info() {
  return array(
    'islandora_cc_badge_badge' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora CC License Badge'),
    ),
  );
}

function islandora_cc_badge_get_license(AbstractObject $object) {
  // Get the CC license URI from the MODS record.
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_cc_badge_path', '/mods:mods/mods:accessCondition[@type="use and reproduction"]')
  );
  if ($xpath_results->length == 0) {
    return FALSE;
  }
  $license = $xpath_results->item(0)->nodeValue;
  if (!$license) {
    return FALSE;
  }
  return $license;
}


/**
 * Implements hook_block_view().
 */
function islandora_cc_badge_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  $to_render = array();

  if ($delta == 'islandora_cc_badge_badge') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      // Check CModel against Badges configuration.
      if (islandora_badges_show_for_cmodel($object)) {
        $license_uri = islandora_cc_badge_get_license($object);
          // Set API endpoint URL
          $url = "http://api.creativecommons.org/rest/1.5";
          $request_url = $url . '/details?license-uri=' . $license_uri;
          // Make the request and get results!
          $result_xml = drupal_http_request($request_url);
          if (!isset($result_xml->error)) {
            $result_json = json_encode($result_xml);
            $result_array = json_decode($result_json, TRUE);
            $result_data = $result_array['data'];
            $result_final = strstr($result_data, '<a rel="license"');
            $result_final = strstr($result_final, '<br/>', true);
          }
        }
      }
      if (isset($result_final)) {
        $to_render['content'] = $result_final;
      }
    }
  return $to_render;
}
