<?php
/**
 * @file
 * Rights Statements Badges
 */

/**
 * Implements hook_menu().
 */
function islandora_rightsstatements_menu() {
  return array(
    'admin/islandora/tools/badges/rightsstatements' => array(
      'title' => 'Rightsstatements badge',
      'description' => 'Configure Rightsstatements.org badge settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_rightsstatements_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_rightsstatements_block_info() {
  return array(
    'islandora_rightsstatements_badge' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora Rightsstatements Badge'),
    ),
  );
}

function islandora_rightsstatements_get_statement(AbstractObject $object) {
  // Get the Rightsstatements URI from the MODS record.
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_rightsstatements_path', '/mods:mods/mods:accessCondition[@type="use and reproduction"')
  );
  if ($xpath_results->length == 0) {
    return FALSE;
  }
  $rightsstatement = $xpath_results->item(0)->nodeValue;
  if (!$rightsstatement) {
    return FALSE;
  }
  return $rightsstatement;
}

function islandora_rightsstatements_get_solr(AbstractObject $object) {

}


/**
 * Implements hook_block_view().
 */
function islandora_rightsstatements_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  module_load_include('inc', 'islandora_rightsstatements', 'includes/utilities');
  $to_render = array();

  if ($delta == 'islandora_rightsstatements_badge') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      // Check CModel against Badges configuration.
      if (islandora_badges_show_for_cmodel($object)) {
        $uri = islandora_rightsstatements_get_statement($object);
        $badge = islandora_rightsstatements_get_html($uri);
        $to_render['content'] = $badge;
      }
    }
  }
  return $to_render;
}
